//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyossUpgradeScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UsertableId { get; set; }
        public string loginUIid { get; set; }
        public string MaxisId { get; set; }
        public string DisplayName { get; set; }
        public string Department { get; set; }
        public string Phone { get; set; }
        public string WorkforceId { get; set; }
        public string SupervisorId { get; set; }
        public string SupervisorName { get; set; }
        public string Email { get; set; }
        public string UserStatus { get; set; }
        public string UserIdentification { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string UserRoles { get; set; }
        public string Applications { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SupervisorEmail { get; set; }
    }
}
